<?php

/**
 * @file
 * Customizations for WWU.
 */

/**
 * Implements hook_islandora_oai_get_xsl_files().
 */
function wwudora_islandora_oai_get_xsl_files() {
  $module_path = drupal_get_path('module', 'wwudora');
  return array(
    "$module_path/xml/wwu_mods_to_dc.xsl" => 'wwu_mods_to_dc.xsl',
  );
}

/**
 * Implements hook_islandora_datastream_ingested().
 */
/*
function wwudora_islandora_datastream_ingested($object, $datastream) {
  module_load_include('inc', 'wwudora', 'includes/inherit_xacml_from_compound_parent');
  wwudora_inherit_xacml_from_compound_parent($object, $datastream);
}*/

/**
 * Implements hook_islandora_datastream_modified().
 */
/*
function wwudora_islandora_datastream_modified($object, $datastream, $params) {
  module_load_include('inc', 'wwudora', 'includes/inherit_xacml_from_compound_parent');
  wwudora_inherit_xacml_from_compound_parent($object, $datastream);
}*/

/**
 * Implements hook_islandora_compound_object_children_added_to_parent().
 */
function wwudora_islandora_compound_object_children_added_to_parent($children, $parent_pids) {
  $parent = islandora_object_load(current($parent_pids));
  foreach ($children as $child) {
    $child->relationships->remove(ISLANDORA_RELS_EXT_URI, 'inheritXacmlFrom', NULL, RELS_TYPE_URI);
    $child->relationships->add(ISLANDORA_RELS_EXT_URI, 'inheritXacmlFrom', $parent->id, RELS_TYPE_URI);
    if ($parent['POLICY']) {
      $xacml = new IslandoraXacml($child, $parent['POLICY']->content);
      $xacml->writeBackToFedora();
    }
    elseif ($child['POLICY']) {
      // Removing Child's existing Policy if new Parent doesn't have one.
      $xacml = new IslandoraXacml($child);
      $xacml->datastreamRule->clear();
      $xacml->managementRule->clear();
      $xacml->viewingRule->clear();
      $xacml->writeBackToFedora();
    }
  }
}

/**
 * Content model specific version of hook_islandora_derivative().
 *
 * @see hook_cmodel_pid_islandora_derivative()
 */
function wwudora_islandora_compoundCModel_islandora_derivative($object, $ds_modified_params = array()) {
  dpm($object, "DERIV - OBJECT");
  dpm($ds_modified_params, "DERIV - DS PARAMS");
  $derivatives[] = array(
    'source_dsid' => 'POLICY',
    'weight' => '0',
    'function' => array(
      'wwudora_policy_to_children_derivatives',
    ),
    'file' => drupal_get_path('module', 'wwudora') . '/includes/derivatives.inc',
  );
  return $derivatives;
}
