<?php

/**
 * @file
 * Customizations for WWU.
 */

/**
 * Implements hook_islandora_oai_get_xsl_files().
 */
function wwudora_islandora_oai_get_xsl_files() {
  $module_path = drupal_get_path('module', 'wwudora');
  return array(
    "$module_path/xml/wwu_mods_to_dc.xsl" => 'wwu_mods_to_dc.xsl',
  );
}

/**
 * Implements hook_islandora_datastream_ingested().
 */
function wwudora_islandora_datastream_ingested($object, $datastream) {
  wwudora_inherit_xacml_from_compound_parent($object, $datastream);
}

/**
 * Implements hook_islandora_datastream_modified().
 */
function wwudora_islandora_datastream_modified($object, $datastream, $params) {
  wwudora_inherit_xacml_from_compound_parent($object, $datastream);
}

/**
 * Implements hook_islandora_compound_object_children_added_to_parent().
 */
function wwudora_islandora_compound_object_children_added_to_parent($children, $parent_pids) {
  $parent = islandora_object_load(current($parent_pids));
  if ($parent['POLICY']) {
    foreach ($children as $child) {
      $child->relationships->add(ISLANDORA_RELS_EXT_URI, 'inheritXacmlFrom', $parent->id, RELS_TYPE_URI);
      $xacml = new IslandoraXacml($child, $parent['POLICY']->content);
      $xacml->writeBackToFedora();
    }
  }
}

/**
 * Apply parent policies to children of compound objects if policy is ingested or modified.
 *
 * @param AbstractObject $object
 *   An AbstractObject of the parent object.
 * @param AbstractDatastream $datastream
 *   An AbstractDatastream of the datastream added to the parent object.
 */
function wwudora_inherit_xacml_from_compound_parent(AbstractObject $object, AbstractDatastream $datastream) {
  if ($datastream->id == "POLICY" && in_array("islandora:compoundCModel", $object->models)) {
    $children = islandora_compound_object_get_parts($object, TRUE);
    foreach ($children as $child) {
      $childObj = islandora_object_load($child['pid']);
      $childObj->relationships->add(ISLANDORA_RELS_EXT_URI, 'inheritXacmlFrom', $object->id, RELS_TYPE_URI);
      $xacml = new IslandoraXacml($childObj, $object['POLICY']->content);
      $xacml->writeBackToFedora();
    }
  }
}
